### ISSUE TITLE
:secure_validatable doesn't set @minimum_password_length

### ISSUE THREAD

**Issue by dredupuika** [devise-security/devise-security#290]
devise :validatable does this
```# Sets minimum password length to show to user
def set_minimum_password_length
  if devise_mapping.validatable?
    @minimum_password_length = resource_class.password_length.min
  end
end
```

**Comment by oniofchaos** [comment]
Hi @dredupuika. I'm not sure what your issue is about. Is it a bug report, a feature request, or something else?

**Comment by dredupuika** [comment]
Obviously a bug. 
Since :secure_validatable is a replacement for the original :validatable it should not brake any functionality.
In this case it makes the original forms in devise less user friendly. As a result 2 devise controllers must be overriden to fix this.

It should at least be mentioned in the readme.

**Comment by oniofchaos** [comment]
Can you share with me what controllers / methods you override in order to fix this?

**Comment by dredupuika** [comment]
I haven't finished and tested it thoroughly. And I consider it a temporary fix.
But since devise uses [set_minimum_password_length](https://github.com/heartcombo/devise/search?q=set_minimum_password_length) in 2 controllers. So I made custom controllers for **registrations** and **passwords** with this method:
```
def set_minimum_password_length
  if devise_mapping.secure_validatable?
    @minimum_password_length = resource_class.password_length.min
    @minimum_password_complexity = resource_class.password_complexity
  else
    super
  end
end
```

however i do think that this problem should be addressed by overriding the devise_controller directly.

**Comment by oniofchaos** [comment]
Ok great! I have some ideas on how to address this. I'll post back once I've been able to explore it.

**Comment by oniofchaos** [comment]
Can you test with https://github.com/oniofchaos/devise-security/tree/validatable and see if it solves the problem? You shouldn't need any controller overrides anymore on either controller.

**Comment by dredupuika** [comment]
Yeah. Works as expected.

I will be keeping those controllers for now since they expose the complexity requirements to the form in the same manner as devise does.
But that's probably feature for the future.

Thanks.

**Comment by oniofchaos** [comment]
Can you elaborate on how you're using the exposed complexity requirements? I'd be happy to add those too.

**Comment by dredupuika** [comment]
After this fix.
In the controller:
```
def set_minimum_password_length
  @minimum_password_complexity = resource_class.password_complexity if devise_mapping.secure_validatable?
  super
end
```

In the form: (I use the bootstrap versions)
```
# original
- if @minimum_password_length
  %small.form-text.text-muted= t('devise.shared.minimum_password_length', count: @minimum_password_length)
# addition
- if @minimum_password_complexity
  - @minimum_password_complexity.each do |k, v|
    %small.form-text.text-muted= t("devise.password_complexity.#{k}", count: v)
```

Translations:
```
en:
  errors:
    messages:
      password_complexity:
        digit:
          one: must contain at least one digit
          other: must contain at least %{count} numerals
        lower:
          one: must contain at least one lower-case letter
          other: must contain at least %{count} lower-case letters
        symbol:
          one: must contain at least one punctuation mark or symbol
          other: must contain at least %{count} punctuation marks or symbols
        upper:
          one: must contain at least one upper-case letter
          other: must contain at least %{count} upper-case letters
```

**Comment by oniofchaos** [comment]
Ok, can you try one more time? :)

The controller should set `@minimum_password_complexity` for you now.

**Comment by dredupuika** [comment]
Seems it reverted to not setting @minimum_password_length or @minimum_password_complexity.
How is set_secure_validatable_information invoked?
Do i have to do it manualy?

i would keep it as
```
define_method :set_minimum_password_length do
  if devise_mapping.validatable?
    @minimum_password_length = resource_class.password_length.min
  elsif devise_mapping.secure_validatable?
    @minimum_password_length = resource_class.password_length.min
    @minimum_password_complexity = resource_class.password_complexity
  end
end
```
as it was since devise calls set_minimum_password_length, but i don't see any reference to set_secure_validatable_information.

**Comment by dredupuika** [comment]
On second thought. the original set_minimum_password_length should be overriden with something that calls super in case devise changes this method in the future. e.g.
```
define_method :set_minimum_password_length do
  if devise_mapping.secure_validatable?
    @minimum_password_length = resource_class.password_length.min
    @minimum_password_complexity = resource_class.password_complexity
  end
  super
end

**Comment by oniofchaos** [comment]
Ok, try again, I think I fixed it. I added a `before_action` to call the new method.

The reason I changed the naming was that I didn't want to override `set_minimum_password_length` for the exact reason you listed: in case devise changes the method. The (weird) way that we're patching right now actually appears to override the method, so calling `super` wouldn't do anything.

**Comment by dredupuika** [comment]
```
module SecureValidatableInformation
  extend ActiveSupport::Concern

  included do
    alias_method :original_set_minimum_password_length, :set_minimum_password_length
    
    define_method :set_minimum_password_length do
      if devise_mapping.secure_validatable?
        @minimum_password_complexity = resource_class.password_complexity
      end
      original_set_minimum_password_length
    end
  end
end
```
then wouldn't this make more sense?

Not fond of prepending this to all actions.

**Comment by oniofchaos** [comment]
Wow! I didn't even think of using alias. That's brilliant. Thanks so much for the suggestion. That definitely makes more sense than prepending to all actions. 🤦 

I pushed up an update that uses that strategy. If that works, I'm going to move this to a pull request.

**Comment by dredupuika** [comment]
works nice!

I think all that is left is a mention in the readme about the way the forms need to be updated.
e.g.
```
<% if @minimum_password_complexity %>
  <% @minimum_password_complexity.each do |k, v| %>
    <em><%= t("devise.password_complexity.#{k}", count: v) %></em><br />
  <% end %>
<% end %>
```
and the translations are the exact ones as the ones for error mesages.
might even use a YAML anchor.

**Comment by oniofchaos** [comment]
> might even use a YAML anchor.

Not sure what you mean by this

**Comment by dredupuika** [comment]
this should copy all the content errors.messages.password_complexity to devise.password_complexity
```
en:
  errors:
    messages:
      password_complexity: &password_complexity_common
        digit: and whatever follows
  devise:
    password_complexity: *password_complexity_common
```
